services:
  mongodb:
    image: mongo:6.0         # MongoDB version
    container_name: mongodb  # Name of the container
    restart: always
    ports:
      - "27017:27017"        # Expose MongoDB on localhost:27017
    volumes:
      - mongo-data:/data/db  # Persist data locally

  mongo-express:
    image: mongo-express:1.0
    container_name: mongo-express
    restart: always
    ports:
      - "8082:8082"          # Expose Mongo Express on localhost:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123

volumes:
  mongo-data:
